export const GET_DATA = 'GET_DATA';
export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_SORTBY = 'UPDATE_SORTBY';
export const UPDATE_UPVOTE = 'UPDATE_UPVOTE';
export const CHANGE_SUGGCLICKED = 'CHANGE_SUGGCLICKED';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_ACTIVEREQ = 'SET_ACTIVEREQ';
export const COMMENTS_COUNT = 'COMMENTS_COUNT';
