export const GET_DATA = 'GET_DATA';
export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_SORTBY = 'UPDATE_SORTBY';
export const UPDATE_UPVOTE = 'UPDATE_UPVOTE';
export const CHANGE_SUGGCLICKED = 'CHANGE_SUGGCLICKED';
